services:
  postgres:
    container_name: container_ingressos
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=db_ingressos
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
