-- AlterTable
ALTER TABLE "tb_assento" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "tb_evento" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "eventDate" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "tb_resevation_history" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "tb_ticket" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(0);
